package com.zhiyiweiye.medicinebox.api.infrastructure.persistence.mapper;

import com.zhiyiweiye.medicinebox.api.infrastructure.persistence.po.CustUserMessage;

public interface CustUserMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_user_message
     *
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_user_message
     *
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    int insert(CustUserMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_user_message
     *
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    int insertSelective(CustUserMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_user_message
     *
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    CustUserMessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_user_message
     *
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    int updateByPrimaryKeySelective(CustUserMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_user_message
     *
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    int updateByPrimaryKey(CustUserMessage record);


}