package com.zhiyiweiye.medicinebox.api.infrastructure.persistence.mapper;

import com.zhiyiweiye.medicinebox.api.infrastructure.persistence.po.CustTempIdentifycode;

public interface CustTempIdentifycodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_temp_identifycode
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_temp_identifycode
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    int insert(CustTempIdentifycode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_temp_identifycode
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    int insertSelective(CustTempIdentifycode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_temp_identifycode
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    CustTempIdentifycode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_temp_identifycode
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    int updateByPrimaryKeySelective(CustTempIdentifycode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_temp_identifycode
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    int updateByPrimaryKey(CustTempIdentifycode record);
}