package com.zhiyiweiye.medicinebox.api.infrastructure.persistence.mapper;

import com.zhiyiweiye.medicinebox.api.infrastructure.persistence.po.DApplicationPay;
import com.zhiyiweiye.medicinebox.api.infrastructure.persistence.po.DApplicationPayWithBLOBs;

public interface DApplicationPayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_application_pay
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    int deleteByPrimaryKey(Long appApplicationNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_application_pay
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    int insert(DApplicationPayWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_application_pay
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    int insertSelective(DApplicationPayWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_application_pay
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    DApplicationPayWithBLOBs selectByPrimaryKey(Long appApplicationNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_application_pay
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    int updateByPrimaryKeySelective(DApplicationPayWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_application_pay
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(DApplicationPayWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_application_pay
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    int updateByPrimaryKey(DApplicationPay record);
}