package com.zhiyiweiye.medicinebox.api.infrastructure.persistence.mapper;

import com.zhiyiweiye.medicinebox.api.infrastructure.persistence.po.NoticeSendflow;

public interface NoticeSendflowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_sendflow
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_sendflow
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    int insert(NoticeSendflow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_sendflow
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    int insertSelective(NoticeSendflow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_sendflow
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    NoticeSendflow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_sendflow
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    int updateByPrimaryKeySelective(NoticeSendflow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_sendflow
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    int updateByPrimaryKey(NoticeSendflow record);
}