package com.zhiyiweiye.medicinebox.api.infrastructure.persistence.po;

import java.util.Date;

public class CustUserMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_user_message.id
     *
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_user_message.code
     *
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_user_message.username
     *
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_user_message.mobile
     *
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_user_message.id_no
     *
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    private String idNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_user_message.name
     *
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_user_message.appNo
     *
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    private Long appno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_user_message.is_read
     *
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    private Integer isRead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_user_message.title
     *
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_user_message.content
     *
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_user_message.operate
     *
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    private String operate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_user_message.type
     *
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_user_message.create_time
     *
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_user_message.update_time
     *
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_user_message.id
     *
     * @return the value of cust_user_message.id
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_user_message.id
     *
     * @param id the value for cust_user_message.id
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_user_message.code
     *
     * @return the value of cust_user_message.code
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_user_message.code
     *
     * @param code the value for cust_user_message.code
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_user_message.username
     *
     * @return the value of cust_user_message.username
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_user_message.username
     *
     * @param username the value for cust_user_message.username
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_user_message.mobile
     *
     * @return the value of cust_user_message.mobile
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_user_message.mobile
     *
     * @param mobile the value for cust_user_message.mobile
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_user_message.id_no
     *
     * @return the value of cust_user_message.id_no
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    public String getIdNo() {
        return idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_user_message.id_no
     *
     * @param idNo the value for cust_user_message.id_no
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    public void setIdNo(String idNo) {
        this.idNo = idNo == null ? null : idNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_user_message.name
     *
     * @return the value of cust_user_message.name
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_user_message.name
     *
     * @param name the value for cust_user_message.name
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_user_message.appNo
     *
     * @return the value of cust_user_message.appNo
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    public Long getAppno() {
        return appno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_user_message.appNo
     *
     * @param appno the value for cust_user_message.appNo
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    public void setAppno(Long appno) {
        this.appno = appno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_user_message.is_read
     *
     * @return the value of cust_user_message.is_read
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    public Integer getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_user_message.is_read
     *
     * @param isRead the value for cust_user_message.is_read
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    public void setIsRead(Integer isRead) {
        this.isRead = isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_user_message.title
     *
     * @return the value of cust_user_message.title
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_user_message.title
     *
     * @param title the value for cust_user_message.title
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_user_message.content
     *
     * @return the value of cust_user_message.content
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_user_message.content
     *
     * @param content the value for cust_user_message.content
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_user_message.operate
     *
     * @return the value of cust_user_message.operate
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    public String getOperate() {
        return operate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_user_message.operate
     *
     * @param operate the value for cust_user_message.operate
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    public void setOperate(String operate) {
        this.operate = operate == null ? null : operate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_user_message.type
     *
     * @return the value of cust_user_message.type
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_user_message.type
     *
     * @param type the value for cust_user_message.type
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_user_message.create_time
     *
     * @return the value of cust_user_message.create_time
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_user_message.create_time
     *
     * @param createTime the value for cust_user_message.create_time
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_user_message.update_time
     *
     * @return the value of cust_user_message.update_time
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_user_message.update_time
     *
     * @param updateTime the value for cust_user_message.update_time
     * @mbg.generated Fri Aug 31 10:39:22 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}