package com.zhiyiweiye.medicinebox.api.infrastructure.persistence.po;

public class CustTempIdentifycode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_temp_identifycode.ID
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_temp_identifycode.USERNAME
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_temp_identifycode.MOBILENO
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String mobileno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_temp_identifycode.IDENTIFYCODE
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String identifycode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_temp_identifycode.SEND_IDENTIFYCODE_TIME
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String sendIdentifycodeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_temp_identifycode.CREATE_TIME
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_temp_identifycode.IP
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String ip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_temp_identifycode.ID
     *
     * @return the value of cust_temp_identifycode.ID
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_temp_identifycode.ID
     *
     * @param id the value for cust_temp_identifycode.ID
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_temp_identifycode.USERNAME
     *
     * @return the value of cust_temp_identifycode.USERNAME
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_temp_identifycode.USERNAME
     *
     * @param username the value for cust_temp_identifycode.USERNAME
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_temp_identifycode.MOBILENO
     *
     * @return the value of cust_temp_identifycode.MOBILENO
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getMobileno() {
        return mobileno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_temp_identifycode.MOBILENO
     *
     * @param mobileno the value for cust_temp_identifycode.MOBILENO
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setMobileno(String mobileno) {
        this.mobileno = mobileno == null ? null : mobileno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_temp_identifycode.IDENTIFYCODE
     *
     * @return the value of cust_temp_identifycode.IDENTIFYCODE
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getIdentifycode() {
        return identifycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_temp_identifycode.IDENTIFYCODE
     *
     * @param identifycode the value for cust_temp_identifycode.IDENTIFYCODE
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setIdentifycode(String identifycode) {
        this.identifycode = identifycode == null ? null : identifycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_temp_identifycode.SEND_IDENTIFYCODE_TIME
     *
     * @return the value of cust_temp_identifycode.SEND_IDENTIFYCODE_TIME
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getSendIdentifycodeTime() {
        return sendIdentifycodeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_temp_identifycode.SEND_IDENTIFYCODE_TIME
     *
     * @param sendIdentifycodeTime the value for cust_temp_identifycode.SEND_IDENTIFYCODE_TIME
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setSendIdentifycodeTime(String sendIdentifycodeTime) {
        this.sendIdentifycodeTime = sendIdentifycodeTime == null ? null : sendIdentifycodeTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_temp_identifycode.CREATE_TIME
     *
     * @return the value of cust_temp_identifycode.CREATE_TIME
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_temp_identifycode.CREATE_TIME
     *
     * @param createTime the value for cust_temp_identifycode.CREATE_TIME
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_temp_identifycode.IP
     *
     * @return the value of cust_temp_identifycode.IP
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_temp_identifycode.IP
     *
     * @param ip the value for cust_temp_identifycode.IP
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }
}