package com.zhiyiweiye.medicinebox.api.infrastructure.persistence.po;

public class DApplicationPayWithBLOBs extends DApplicationPay {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_application_pay.app_tel_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String appTelDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_application_pay.app_blacklist_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String appBlacklistDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_application_pay.app_pic_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String appPicDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_application_pay.app_approval_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String appApprovalDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_application_pay.app_electric_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String appElectricDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_application_pay.app_face_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String appFaceDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_application_pay.app_contract_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String appContractDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_application_pay.app_sitedesc_charge
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String appSitedescCharge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_application_pay.app_privilege_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String appPrivilegeDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_application_pay.app_teldesc_charge
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String appTeldescCharge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_application_pay.app_delivery_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String appDeliveryDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_application_pay.app_close_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String appCloseDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_application_pay.app_saledesc_charge
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String appSaledescCharge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_application_pay.app_approvaldesc_charge
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String appApprovaldescCharge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_application_pay.app_receive_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String appReceiveDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_application_pay.app_check_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String appCheckDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_application_pay.approval_desc1
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String approvalDesc1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_application_pay.approval_desc2
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String approvalDesc2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_application_pay.approval_desc3
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String approvalDesc3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_application_pay.approval_desc4
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String approvalDesc4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_application_pay.collection_Desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String collectionDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_application_pay.app_fina_check_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String appFinaCheckDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_application_pay.cus_tel_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String cusTelDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_application_pay.REJECT_DESC
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String rejectDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_application_pay.AGREEMENT_DESC
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String agreementDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_application_pay.ATTACHMENT_DESC
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String attachmentDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_application_pay.LOCAL_DESC
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String localDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_application_pay.marketChiefDesc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String marketchiefdesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_application_pay.PRODUCT_DETAIL
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String productDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_application_pay.withIndiaDesc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String withindiadesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_application_pay.app_electriccus_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String appElectriccusDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_application_pay.APP_DESC
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String appDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_application_pay.BROWSER_STR
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String browserStr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_application_pay.app_tel_desc
     *
     * @return the value of d_application_pay.app_tel_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getAppTelDesc() {
        return appTelDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_application_pay.app_tel_desc
     *
     * @param appTelDesc the value for d_application_pay.app_tel_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setAppTelDesc(String appTelDesc) {
        this.appTelDesc = appTelDesc == null ? null : appTelDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_application_pay.app_blacklist_desc
     *
     * @return the value of d_application_pay.app_blacklist_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getAppBlacklistDesc() {
        return appBlacklistDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_application_pay.app_blacklist_desc
     *
     * @param appBlacklistDesc the value for d_application_pay.app_blacklist_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setAppBlacklistDesc(String appBlacklistDesc) {
        this.appBlacklistDesc = appBlacklistDesc == null ? null : appBlacklistDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_application_pay.app_pic_desc
     *
     * @return the value of d_application_pay.app_pic_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getAppPicDesc() {
        return appPicDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_application_pay.app_pic_desc
     *
     * @param appPicDesc the value for d_application_pay.app_pic_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setAppPicDesc(String appPicDesc) {
        this.appPicDesc = appPicDesc == null ? null : appPicDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_application_pay.app_approval_desc
     *
     * @return the value of d_application_pay.app_approval_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getAppApprovalDesc() {
        return appApprovalDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_application_pay.app_approval_desc
     *
     * @param appApprovalDesc the value for d_application_pay.app_approval_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setAppApprovalDesc(String appApprovalDesc) {
        this.appApprovalDesc = appApprovalDesc == null ? null : appApprovalDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_application_pay.app_electric_desc
     *
     * @return the value of d_application_pay.app_electric_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getAppElectricDesc() {
        return appElectricDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_application_pay.app_electric_desc
     *
     * @param appElectricDesc the value for d_application_pay.app_electric_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setAppElectricDesc(String appElectricDesc) {
        this.appElectricDesc = appElectricDesc == null ? null : appElectricDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_application_pay.app_face_desc
     *
     * @return the value of d_application_pay.app_face_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getAppFaceDesc() {
        return appFaceDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_application_pay.app_face_desc
     *
     * @param appFaceDesc the value for d_application_pay.app_face_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setAppFaceDesc(String appFaceDesc) {
        this.appFaceDesc = appFaceDesc == null ? null : appFaceDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_application_pay.app_contract_desc
     *
     * @return the value of d_application_pay.app_contract_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getAppContractDesc() {
        return appContractDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_application_pay.app_contract_desc
     *
     * @param appContractDesc the value for d_application_pay.app_contract_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setAppContractDesc(String appContractDesc) {
        this.appContractDesc = appContractDesc == null ? null : appContractDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_application_pay.app_sitedesc_charge
     *
     * @return the value of d_application_pay.app_sitedesc_charge
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getAppSitedescCharge() {
        return appSitedescCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_application_pay.app_sitedesc_charge
     *
     * @param appSitedescCharge the value for d_application_pay.app_sitedesc_charge
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setAppSitedescCharge(String appSitedescCharge) {
        this.appSitedescCharge = appSitedescCharge == null ? null : appSitedescCharge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_application_pay.app_privilege_desc
     *
     * @return the value of d_application_pay.app_privilege_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getAppPrivilegeDesc() {
        return appPrivilegeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_application_pay.app_privilege_desc
     *
     * @param appPrivilegeDesc the value for d_application_pay.app_privilege_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setAppPrivilegeDesc(String appPrivilegeDesc) {
        this.appPrivilegeDesc = appPrivilegeDesc == null ? null : appPrivilegeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_application_pay.app_teldesc_charge
     *
     * @return the value of d_application_pay.app_teldesc_charge
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getAppTeldescCharge() {
        return appTeldescCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_application_pay.app_teldesc_charge
     *
     * @param appTeldescCharge the value for d_application_pay.app_teldesc_charge
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setAppTeldescCharge(String appTeldescCharge) {
        this.appTeldescCharge = appTeldescCharge == null ? null : appTeldescCharge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_application_pay.app_delivery_desc
     *
     * @return the value of d_application_pay.app_delivery_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getAppDeliveryDesc() {
        return appDeliveryDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_application_pay.app_delivery_desc
     *
     * @param appDeliveryDesc the value for d_application_pay.app_delivery_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setAppDeliveryDesc(String appDeliveryDesc) {
        this.appDeliveryDesc = appDeliveryDesc == null ? null : appDeliveryDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_application_pay.app_close_desc
     *
     * @return the value of d_application_pay.app_close_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getAppCloseDesc() {
        return appCloseDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_application_pay.app_close_desc
     *
     * @param appCloseDesc the value for d_application_pay.app_close_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setAppCloseDesc(String appCloseDesc) {
        this.appCloseDesc = appCloseDesc == null ? null : appCloseDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_application_pay.app_saledesc_charge
     *
     * @return the value of d_application_pay.app_saledesc_charge
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getAppSaledescCharge() {
        return appSaledescCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_application_pay.app_saledesc_charge
     *
     * @param appSaledescCharge the value for d_application_pay.app_saledesc_charge
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setAppSaledescCharge(String appSaledescCharge) {
        this.appSaledescCharge = appSaledescCharge == null ? null : appSaledescCharge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_application_pay.app_approvaldesc_charge
     *
     * @return the value of d_application_pay.app_approvaldesc_charge
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getAppApprovaldescCharge() {
        return appApprovaldescCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_application_pay.app_approvaldesc_charge
     *
     * @param appApprovaldescCharge the value for d_application_pay.app_approvaldesc_charge
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setAppApprovaldescCharge(String appApprovaldescCharge) {
        this.appApprovaldescCharge = appApprovaldescCharge == null ? null : appApprovaldescCharge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_application_pay.app_receive_desc
     *
     * @return the value of d_application_pay.app_receive_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getAppReceiveDesc() {
        return appReceiveDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_application_pay.app_receive_desc
     *
     * @param appReceiveDesc the value for d_application_pay.app_receive_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setAppReceiveDesc(String appReceiveDesc) {
        this.appReceiveDesc = appReceiveDesc == null ? null : appReceiveDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_application_pay.app_check_desc
     *
     * @return the value of d_application_pay.app_check_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getAppCheckDesc() {
        return appCheckDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_application_pay.app_check_desc
     *
     * @param appCheckDesc the value for d_application_pay.app_check_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setAppCheckDesc(String appCheckDesc) {
        this.appCheckDesc = appCheckDesc == null ? null : appCheckDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_application_pay.approval_desc1
     *
     * @return the value of d_application_pay.approval_desc1
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getApprovalDesc1() {
        return approvalDesc1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_application_pay.approval_desc1
     *
     * @param approvalDesc1 the value for d_application_pay.approval_desc1
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setApprovalDesc1(String approvalDesc1) {
        this.approvalDesc1 = approvalDesc1 == null ? null : approvalDesc1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_application_pay.approval_desc2
     *
     * @return the value of d_application_pay.approval_desc2
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getApprovalDesc2() {
        return approvalDesc2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_application_pay.approval_desc2
     *
     * @param approvalDesc2 the value for d_application_pay.approval_desc2
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setApprovalDesc2(String approvalDesc2) {
        this.approvalDesc2 = approvalDesc2 == null ? null : approvalDesc2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_application_pay.approval_desc3
     *
     * @return the value of d_application_pay.approval_desc3
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getApprovalDesc3() {
        return approvalDesc3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_application_pay.approval_desc3
     *
     * @param approvalDesc3 the value for d_application_pay.approval_desc3
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setApprovalDesc3(String approvalDesc3) {
        this.approvalDesc3 = approvalDesc3 == null ? null : approvalDesc3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_application_pay.approval_desc4
     *
     * @return the value of d_application_pay.approval_desc4
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getApprovalDesc4() {
        return approvalDesc4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_application_pay.approval_desc4
     *
     * @param approvalDesc4 the value for d_application_pay.approval_desc4
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setApprovalDesc4(String approvalDesc4) {
        this.approvalDesc4 = approvalDesc4 == null ? null : approvalDesc4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_application_pay.collection_Desc
     *
     * @return the value of d_application_pay.collection_Desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getCollectionDesc() {
        return collectionDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_application_pay.collection_Desc
     *
     * @param collectionDesc the value for d_application_pay.collection_Desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setCollectionDesc(String collectionDesc) {
        this.collectionDesc = collectionDesc == null ? null : collectionDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_application_pay.app_fina_check_desc
     *
     * @return the value of d_application_pay.app_fina_check_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getAppFinaCheckDesc() {
        return appFinaCheckDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_application_pay.app_fina_check_desc
     *
     * @param appFinaCheckDesc the value for d_application_pay.app_fina_check_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setAppFinaCheckDesc(String appFinaCheckDesc) {
        this.appFinaCheckDesc = appFinaCheckDesc == null ? null : appFinaCheckDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_application_pay.cus_tel_desc
     *
     * @return the value of d_application_pay.cus_tel_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getCusTelDesc() {
        return cusTelDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_application_pay.cus_tel_desc
     *
     * @param cusTelDesc the value for d_application_pay.cus_tel_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setCusTelDesc(String cusTelDesc) {
        this.cusTelDesc = cusTelDesc == null ? null : cusTelDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_application_pay.REJECT_DESC
     *
     * @return the value of d_application_pay.REJECT_DESC
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getRejectDesc() {
        return rejectDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_application_pay.REJECT_DESC
     *
     * @param rejectDesc the value for d_application_pay.REJECT_DESC
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setRejectDesc(String rejectDesc) {
        this.rejectDesc = rejectDesc == null ? null : rejectDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_application_pay.AGREEMENT_DESC
     *
     * @return the value of d_application_pay.AGREEMENT_DESC
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getAgreementDesc() {
        return agreementDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_application_pay.AGREEMENT_DESC
     *
     * @param agreementDesc the value for d_application_pay.AGREEMENT_DESC
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setAgreementDesc(String agreementDesc) {
        this.agreementDesc = agreementDesc == null ? null : agreementDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_application_pay.ATTACHMENT_DESC
     *
     * @return the value of d_application_pay.ATTACHMENT_DESC
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getAttachmentDesc() {
        return attachmentDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_application_pay.ATTACHMENT_DESC
     *
     * @param attachmentDesc the value for d_application_pay.ATTACHMENT_DESC
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setAttachmentDesc(String attachmentDesc) {
        this.attachmentDesc = attachmentDesc == null ? null : attachmentDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_application_pay.LOCAL_DESC
     *
     * @return the value of d_application_pay.LOCAL_DESC
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getLocalDesc() {
        return localDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_application_pay.LOCAL_DESC
     *
     * @param localDesc the value for d_application_pay.LOCAL_DESC
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setLocalDesc(String localDesc) {
        this.localDesc = localDesc == null ? null : localDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_application_pay.marketChiefDesc
     *
     * @return the value of d_application_pay.marketChiefDesc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getMarketchiefdesc() {
        return marketchiefdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_application_pay.marketChiefDesc
     *
     * @param marketchiefdesc the value for d_application_pay.marketChiefDesc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setMarketchiefdesc(String marketchiefdesc) {
        this.marketchiefdesc = marketchiefdesc == null ? null : marketchiefdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_application_pay.PRODUCT_DETAIL
     *
     * @return the value of d_application_pay.PRODUCT_DETAIL
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getProductDetail() {
        return productDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_application_pay.PRODUCT_DETAIL
     *
     * @param productDetail the value for d_application_pay.PRODUCT_DETAIL
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setProductDetail(String productDetail) {
        this.productDetail = productDetail == null ? null : productDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_application_pay.withIndiaDesc
     *
     * @return the value of d_application_pay.withIndiaDesc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getWithindiadesc() {
        return withindiadesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_application_pay.withIndiaDesc
     *
     * @param withindiadesc the value for d_application_pay.withIndiaDesc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setWithindiadesc(String withindiadesc) {
        this.withindiadesc = withindiadesc == null ? null : withindiadesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_application_pay.app_electriccus_desc
     *
     * @return the value of d_application_pay.app_electriccus_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getAppElectriccusDesc() {
        return appElectriccusDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_application_pay.app_electriccus_desc
     *
     * @param appElectriccusDesc the value for d_application_pay.app_electriccus_desc
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setAppElectriccusDesc(String appElectriccusDesc) {
        this.appElectriccusDesc = appElectriccusDesc == null ? null : appElectriccusDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_application_pay.APP_DESC
     *
     * @return the value of d_application_pay.APP_DESC
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getAppDesc() {
        return appDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_application_pay.APP_DESC
     *
     * @param appDesc the value for d_application_pay.APP_DESC
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setAppDesc(String appDesc) {
        this.appDesc = appDesc == null ? null : appDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_application_pay.BROWSER_STR
     *
     * @return the value of d_application_pay.BROWSER_STR
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getBrowserStr() {
        return browserStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_application_pay.BROWSER_STR
     *
     * @param browserStr the value for d_application_pay.BROWSER_STR
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setBrowserStr(String browserStr) {
        this.browserStr = browserStr == null ? null : browserStr.trim();
    }
}