package com.zhiyiweiye.medicinebox.api.infrastructure.persistence.po;

import java.util.Date;

public class NoticeSendflow {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_sendflow.ID
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_sendflow.USERNAME
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_sendflow.BUSS_NO
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String bussNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_sendflow.TITLE
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_sendflow.TEMPLATE
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String template;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_sendflow.CONTENT
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_sendflow.NTYPE
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String ntype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_sendflow.RECEIVE_TELPHONE
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String receiveTelphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_sendflow.RECEIVE_EMAIL
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String receiveEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_sendflow.SEND_TIME
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private Date sendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_sendflow.SEND_STATUS
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String sendStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_sendflow.OPERATOR
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_sendflow.SEND_FLAG
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String sendFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_sendflow.CREATE_TIME
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_sendflow.SEND_NUMBER
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String sendNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_sendflow.create_user
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_sendflow.update_date
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_sendflow.update_user
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_sendflow.update_time
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_sendflow.AC_ENDDATE
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String acEnddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_sendflow.AC_NAME
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String acName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_sendflow.AC_STARTDATE
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    private String acStartdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_sendflow.ID
     *
     * @return the value of notice_sendflow.ID
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_sendflow.ID
     *
     * @param id the value for notice_sendflow.ID
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_sendflow.USERNAME
     *
     * @return the value of notice_sendflow.USERNAME
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_sendflow.USERNAME
     *
     * @param username the value for notice_sendflow.USERNAME
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_sendflow.BUSS_NO
     *
     * @return the value of notice_sendflow.BUSS_NO
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getBussNo() {
        return bussNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_sendflow.BUSS_NO
     *
     * @param bussNo the value for notice_sendflow.BUSS_NO
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setBussNo(String bussNo) {
        this.bussNo = bussNo == null ? null : bussNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_sendflow.TITLE
     *
     * @return the value of notice_sendflow.TITLE
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_sendflow.TITLE
     *
     * @param title the value for notice_sendflow.TITLE
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_sendflow.TEMPLATE
     *
     * @return the value of notice_sendflow.TEMPLATE
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getTemplate() {
        return template;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_sendflow.TEMPLATE
     *
     * @param template the value for notice_sendflow.TEMPLATE
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setTemplate(String template) {
        this.template = template == null ? null : template.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_sendflow.CONTENT
     *
     * @return the value of notice_sendflow.CONTENT
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_sendflow.CONTENT
     *
     * @param content the value for notice_sendflow.CONTENT
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_sendflow.NTYPE
     *
     * @return the value of notice_sendflow.NTYPE
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getNtype() {
        return ntype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_sendflow.NTYPE
     *
     * @param ntype the value for notice_sendflow.NTYPE
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setNtype(String ntype) {
        this.ntype = ntype == null ? null : ntype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_sendflow.RECEIVE_TELPHONE
     *
     * @return the value of notice_sendflow.RECEIVE_TELPHONE
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getReceiveTelphone() {
        return receiveTelphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_sendflow.RECEIVE_TELPHONE
     *
     * @param receiveTelphone the value for notice_sendflow.RECEIVE_TELPHONE
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setReceiveTelphone(String receiveTelphone) {
        this.receiveTelphone = receiveTelphone == null ? null : receiveTelphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_sendflow.RECEIVE_EMAIL
     *
     * @return the value of notice_sendflow.RECEIVE_EMAIL
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getReceiveEmail() {
        return receiveEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_sendflow.RECEIVE_EMAIL
     *
     * @param receiveEmail the value for notice_sendflow.RECEIVE_EMAIL
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setReceiveEmail(String receiveEmail) {
        this.receiveEmail = receiveEmail == null ? null : receiveEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_sendflow.SEND_TIME
     *
     * @return the value of notice_sendflow.SEND_TIME
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_sendflow.SEND_TIME
     *
     * @param sendTime the value for notice_sendflow.SEND_TIME
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_sendflow.SEND_STATUS
     *
     * @return the value of notice_sendflow.SEND_STATUS
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getSendStatus() {
        return sendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_sendflow.SEND_STATUS
     *
     * @param sendStatus the value for notice_sendflow.SEND_STATUS
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setSendStatus(String sendStatus) {
        this.sendStatus = sendStatus == null ? null : sendStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_sendflow.OPERATOR
     *
     * @return the value of notice_sendflow.OPERATOR
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_sendflow.OPERATOR
     *
     * @param operator the value for notice_sendflow.OPERATOR
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_sendflow.SEND_FLAG
     *
     * @return the value of notice_sendflow.SEND_FLAG
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getSendFlag() {
        return sendFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_sendflow.SEND_FLAG
     *
     * @param sendFlag the value for notice_sendflow.SEND_FLAG
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setSendFlag(String sendFlag) {
        this.sendFlag = sendFlag == null ? null : sendFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_sendflow.CREATE_TIME
     *
     * @return the value of notice_sendflow.CREATE_TIME
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_sendflow.CREATE_TIME
     *
     * @param createTime the value for notice_sendflow.CREATE_TIME
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_sendflow.SEND_NUMBER
     *
     * @return the value of notice_sendflow.SEND_NUMBER
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getSendNumber() {
        return sendNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_sendflow.SEND_NUMBER
     *
     * @param sendNumber the value for notice_sendflow.SEND_NUMBER
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setSendNumber(String sendNumber) {
        this.sendNumber = sendNumber == null ? null : sendNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_sendflow.create_user
     *
     * @return the value of notice_sendflow.create_user
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_sendflow.create_user
     *
     * @param createUser the value for notice_sendflow.create_user
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_sendflow.update_date
     *
     * @return the value of notice_sendflow.update_date
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_sendflow.update_date
     *
     * @param updateDate the value for notice_sendflow.update_date
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_sendflow.update_user
     *
     * @return the value of notice_sendflow.update_user
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_sendflow.update_user
     *
     * @param updateUser the value for notice_sendflow.update_user
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_sendflow.update_time
     *
     * @return the value of notice_sendflow.update_time
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_sendflow.update_time
     *
     * @param updateTime the value for notice_sendflow.update_time
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_sendflow.AC_ENDDATE
     *
     * @return the value of notice_sendflow.AC_ENDDATE
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getAcEnddate() {
        return acEnddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_sendflow.AC_ENDDATE
     *
     * @param acEnddate the value for notice_sendflow.AC_ENDDATE
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setAcEnddate(String acEnddate) {
        this.acEnddate = acEnddate == null ? null : acEnddate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_sendflow.AC_NAME
     *
     * @return the value of notice_sendflow.AC_NAME
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getAcName() {
        return acName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_sendflow.AC_NAME
     *
     * @param acName the value for notice_sendflow.AC_NAME
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setAcName(String acName) {
        this.acName = acName == null ? null : acName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_sendflow.AC_STARTDATE
     *
     * @return the value of notice_sendflow.AC_STARTDATE
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public String getAcStartdate() {
        return acStartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_sendflow.AC_STARTDATE
     *
     * @param acStartdate the value for notice_sendflow.AC_STARTDATE
     *
     * @mbg.generated Wed Aug 08 14:21:37 CST 2018
     */
    public void setAcStartdate(String acStartdate) {
        this.acStartdate = acStartdate == null ? null : acStartdate.trim();
    }
}