package com.zhiyiweiye.medicinebox.api.infrastructure.persistence.po;

public class NoticeConfigure {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_configure.BUSS_ID
     *
     * @mbg.generated Thu Aug 09 14:30:44 CST 2018
     */
    private String bussId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_configure.BUSS_NAME
     *
     * @mbg.generated Thu Aug 09 14:30:44 CST 2018
     */
    private String bussName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_configure.SMS_FLAG
     *
     * @mbg.generated Thu Aug 09 14:30:44 CST 2018
     */
    private String smsFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_configure.SMS_TEMPLATE
     *
     * @mbg.generated Thu Aug 09 14:30:44 CST 2018
     */
    private String smsTemplate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_configure.SMS_SEND_TYPE
     *
     * @mbg.generated Thu Aug 09 14:30:44 CST 2018
     */
    private String smsSendType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_configure.EMAIL_FLAG
     *
     * @mbg.generated Thu Aug 09 14:30:44 CST 2018
     */
    private String emailFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_configure.EMAIL_TEMPLATE
     *
     * @mbg.generated Thu Aug 09 14:30:44 CST 2018
     */
    private String emailTemplate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_configure.EMAIL_SEND_TYPE
     *
     * @mbg.generated Thu Aug 09 14:30:44 CST 2018
     */
    private String emailSendType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_configure.STATION_LETTER_FLAG
     *
     * @mbg.generated Thu Aug 09 14:30:44 CST 2018
     */
    private String stationLetterFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_configure.STATION_LETTER_TEMPLATE
     *
     * @mbg.generated Thu Aug 09 14:30:44 CST 2018
     */
    private String stationLetterTemplate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_configure.STATION_LETTER_SEND_TYPE
     *
     * @mbg.generated Thu Aug 09 14:30:44 CST 2018
     */
    private String stationLetterSendType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_configure.BUSS_ID
     *
     * @return the value of notice_configure.BUSS_ID
     *
     * @mbg.generated Thu Aug 09 14:30:44 CST 2018
     */
    public String getBussId() {
        return bussId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_configure.BUSS_ID
     *
     * @param bussId the value for notice_configure.BUSS_ID
     *
     * @mbg.generated Thu Aug 09 14:30:44 CST 2018
     */
    public void setBussId(String bussId) {
        this.bussId = bussId == null ? null : bussId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_configure.BUSS_NAME
     *
     * @return the value of notice_configure.BUSS_NAME
     *
     * @mbg.generated Thu Aug 09 14:30:44 CST 2018
     */
    public String getBussName() {
        return bussName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_configure.BUSS_NAME
     *
     * @param bussName the value for notice_configure.BUSS_NAME
     *
     * @mbg.generated Thu Aug 09 14:30:44 CST 2018
     */
    public void setBussName(String bussName) {
        this.bussName = bussName == null ? null : bussName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_configure.SMS_FLAG
     *
     * @return the value of notice_configure.SMS_FLAG
     *
     * @mbg.generated Thu Aug 09 14:30:44 CST 2018
     */
    public String getSmsFlag() {
        return smsFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_configure.SMS_FLAG
     *
     * @param smsFlag the value for notice_configure.SMS_FLAG
     *
     * @mbg.generated Thu Aug 09 14:30:44 CST 2018
     */
    public void setSmsFlag(String smsFlag) {
        this.smsFlag = smsFlag == null ? null : smsFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_configure.SMS_TEMPLATE
     *
     * @return the value of notice_configure.SMS_TEMPLATE
     *
     * @mbg.generated Thu Aug 09 14:30:44 CST 2018
     */
    public String getSmsTemplate() {
        return smsTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_configure.SMS_TEMPLATE
     *
     * @param smsTemplate the value for notice_configure.SMS_TEMPLATE
     *
     * @mbg.generated Thu Aug 09 14:30:44 CST 2018
     */
    public void setSmsTemplate(String smsTemplate) {
        this.smsTemplate = smsTemplate == null ? null : smsTemplate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_configure.SMS_SEND_TYPE
     *
     * @return the value of notice_configure.SMS_SEND_TYPE
     *
     * @mbg.generated Thu Aug 09 14:30:44 CST 2018
     */
    public String getSmsSendType() {
        return smsSendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_configure.SMS_SEND_TYPE
     *
     * @param smsSendType the value for notice_configure.SMS_SEND_TYPE
     *
     * @mbg.generated Thu Aug 09 14:30:44 CST 2018
     */
    public void setSmsSendType(String smsSendType) {
        this.smsSendType = smsSendType == null ? null : smsSendType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_configure.EMAIL_FLAG
     *
     * @return the value of notice_configure.EMAIL_FLAG
     *
     * @mbg.generated Thu Aug 09 14:30:44 CST 2018
     */
    public String getEmailFlag() {
        return emailFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_configure.EMAIL_FLAG
     *
     * @param emailFlag the value for notice_configure.EMAIL_FLAG
     *
     * @mbg.generated Thu Aug 09 14:30:44 CST 2018
     */
    public void setEmailFlag(String emailFlag) {
        this.emailFlag = emailFlag == null ? null : emailFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_configure.EMAIL_TEMPLATE
     *
     * @return the value of notice_configure.EMAIL_TEMPLATE
     *
     * @mbg.generated Thu Aug 09 14:30:44 CST 2018
     */
    public String getEmailTemplate() {
        return emailTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_configure.EMAIL_TEMPLATE
     *
     * @param emailTemplate the value for notice_configure.EMAIL_TEMPLATE
     *
     * @mbg.generated Thu Aug 09 14:30:44 CST 2018
     */
    public void setEmailTemplate(String emailTemplate) {
        this.emailTemplate = emailTemplate == null ? null : emailTemplate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_configure.EMAIL_SEND_TYPE
     *
     * @return the value of notice_configure.EMAIL_SEND_TYPE
     *
     * @mbg.generated Thu Aug 09 14:30:44 CST 2018
     */
    public String getEmailSendType() {
        return emailSendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_configure.EMAIL_SEND_TYPE
     *
     * @param emailSendType the value for notice_configure.EMAIL_SEND_TYPE
     *
     * @mbg.generated Thu Aug 09 14:30:44 CST 2018
     */
    public void setEmailSendType(String emailSendType) {
        this.emailSendType = emailSendType == null ? null : emailSendType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_configure.STATION_LETTER_FLAG
     *
     * @return the value of notice_configure.STATION_LETTER_FLAG
     *
     * @mbg.generated Thu Aug 09 14:30:44 CST 2018
     */
    public String getStationLetterFlag() {
        return stationLetterFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_configure.STATION_LETTER_FLAG
     *
     * @param stationLetterFlag the value for notice_configure.STATION_LETTER_FLAG
     *
     * @mbg.generated Thu Aug 09 14:30:44 CST 2018
     */
    public void setStationLetterFlag(String stationLetterFlag) {
        this.stationLetterFlag = stationLetterFlag == null ? null : stationLetterFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_configure.STATION_LETTER_TEMPLATE
     *
     * @return the value of notice_configure.STATION_LETTER_TEMPLATE
     *
     * @mbg.generated Thu Aug 09 14:30:44 CST 2018
     */
    public String getStationLetterTemplate() {
        return stationLetterTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_configure.STATION_LETTER_TEMPLATE
     *
     * @param stationLetterTemplate the value for notice_configure.STATION_LETTER_TEMPLATE
     *
     * @mbg.generated Thu Aug 09 14:30:44 CST 2018
     */
    public void setStationLetterTemplate(String stationLetterTemplate) {
        this.stationLetterTemplate = stationLetterTemplate == null ? null : stationLetterTemplate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_configure.STATION_LETTER_SEND_TYPE
     *
     * @return the value of notice_configure.STATION_LETTER_SEND_TYPE
     *
     * @mbg.generated Thu Aug 09 14:30:44 CST 2018
     */
    public String getStationLetterSendType() {
        return stationLetterSendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_configure.STATION_LETTER_SEND_TYPE
     *
     * @param stationLetterSendType the value for notice_configure.STATION_LETTER_SEND_TYPE
     *
     * @mbg.generated Thu Aug 09 14:30:44 CST 2018
     */
    public void setStationLetterSendType(String stationLetterSendType) {
        this.stationLetterSendType = stationLetterSendType == null ? null : stationLetterSendType.trim();
    }
}